### ISSUE TITLE
Request for permission to translate your blog article in Korean

### ISSUE THREAD

**Issue by emewjin** [mayank99/mayank99#1]
Hello, @mayank99 !
I'm Yujin Lim, a front-end developer At [Korean FE Article Team](https://kofearticle.substack.com/about).

I hope your understand that I couldn't find your email address first, so I'm reaching out through the issue tab.

I came across your article titled ["React Server Components: the Good, the Bad, and the Ugly"](https://www.mayank.co/blog/react-server-components) and was impressed by its content.
I'd like to request your permission to translate it into Korean and publish it on [my blog](https://emewjin.github.io/) and [Korean](https://kofearticle.substack.com/)[FE Article mailing substack](https://kofearticle.substack.com/).
Of course, link to the original article will be provided.

Korean FE Article is an activity that picks good FE articles every week, translates them into Korean, and shares them.
It is not used commercially, and the source must be identified.
Your work is valuable, and I hope to make it accessible to the Korean developers.

Please think about it and reply.

**Comment by mayank99** [comment]
Absolutely not. This is an extremely creepy way of reaching out. It's unacceptable! Have you considered that if you can't find my email, it's because I do not want to be contacted?

Moreover, I would never allow my content to be published on Substack. It's a horrible platform.
